# Generated by Django 5.0.3 on 2024-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_alter_paciente_responsable_de_carga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Registro de socio'},
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado',
            field=models.FileField(null=True, upload_to='certificados/'),
        ),
    ]
