# Generated by Django 5.0.3 on 2024-04-16 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='usuario',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Medico Responsable'),
        ),
    ]
