# Generated by Django 5.0.3 on 2024-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0002_alter_historialclinico_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='observacion',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='Detalle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Problema'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='antecedentefamiliar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='enfermedad',
            field=models.CharField(blank=True, max_length=300, verbose_name='Enfermedad Actual'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='indicacion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Indicacion'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='motivo',
            field=models.CharField(default=1, max_length=300, verbose_name='Motivo de consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='problema',
            field=models.CharField(blank=True, max_length=300, verbose_name='Problema'),
        ),
    ]
