# Generated by Django 5.0.3 on 2024-06-12 20:09

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0004_alter_historialclinico_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialclinico',
            options={'verbose_name_plural': 'Historiales Clínicos'},
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='Detalle',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='antecedentefamiliar',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='enfermedad',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Enfermedad Actual'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='indicacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Indicación'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='motivo',
            field=ckeditor.fields.RichTextField(verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='problema',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Médico Responsable'),
        ),
    ]
