# Generated by Django 5.0.3 on 2024-06-12 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0005_alter_historialclinico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialclinico',
            options={},
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='Detalle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='antecedentefamiliar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='enfermedad',
            field=models.CharField(blank=True, max_length=300, verbose_name='Enfermedad Actual'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='indicacion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Indicacion'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='motivo',
            field=models.CharField(max_length=300, verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='problema',
            field=models.CharField(blank=True, max_length=300, verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Medico Responsable'),
        ),
    ]
