# Generated by Django 5.0.3 on 2024-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0006_alter_historialclinico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='Detalle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Detalle'),
        ),
    ]
