# Generated by Django 5.0.3 on 2024-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0007_alter_historialclinico_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='observacionps',
            field=models.CharField(blank=True, max_length=500, verbose_name='Observación Psiquiátrica'),
        ),
    ]
