# Generated by Django 5.0.3 on 2024-06-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0008_historialclinico_observacionps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='observacionps',
        ),
    ]
