# Generated by Django 5.0.3 on 2024-06-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0009_remove_historialclinico_observacionps'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='area',
            field=models.CharField(choices=[('OD', 'Odontología'), ('CG', 'Consulta General'), ('PS', 'Psiquiatría'), ('OT', 'Otros')], default='CG', max_length=2, verbose_name='Área'),
        ),
    ]
