# Generated by Django 5.0.3 on 2024-08-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('historialesclinicos', '0011_alter_historialclinico_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.area'),
        ),
    ]
