# Generated by Django 5.0.3 on 2024-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0012_alter_historialclinico_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='Detalle',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='antecedentefamiliar',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='enfermedad',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Enfermedad Actual'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='indicacion',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Indicacion'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='problema',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Problema'),
        ),
    ]
