# Generated by Django 5.0.3 on 2024-08-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historialesclinicos', '0013_alter_historialclinico_detalle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialclinico',
            old_name='Detalle',
            new_name='detalle',
        ),
    ]
