# Generated by Django 5.0.3 on 2024-04-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_test_delete_turno'),
        ('turno', '0005_alter_turno_responsable_de_carga_alter_turno_usuario'),
    ]

    operations = [
    ]
