# Generated by Django 5.0.3 on 2024-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0008_alter_turno_options_alter_turno_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('0', 'Presente'), ('1', 'Atendido'), ('2', 'Ausente con aviso'), ('3', 'Ausente sin aviso'), ('4', 'Confirmado'), ('5', 'Cancelado')], default='0', max_length=2, verbose_name='Estado del turno'),
        ),
    ]
