# Generated by Django 5.0.3 on 2024-06-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0007_turno_delete_test'),
        ('turno', '0010_alter_turno_estado'),
    ]

    operations = [
    ]
