# Generated by Django 5.0.3 on 2024-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0010_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='area',
            field=models.CharField(choices=[('OD', 'Odontología'), ('CG', 'Consulta General'), ('PS', 'Psiquiatría'), ('OT', 'Otros')], default='CG', max_length=2, verbose_name='Área'),
        ),
    ]
