# Generated by Django 5.0.3 on 2024-06-27 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0011_merge_0007_turno_delete_test_0010_alter_turno_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente de Confirmación'), ('1', 'Atendido'), ('2', 'Ausente con aviso'), ('3', 'Ausente sin aviso'), ('4', 'Confirmado'), ('5', 'Cancelado')], default='0', max_length=2, verbose_name='Estado del turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.CharField(choices=[('0', '8:00 - 8:15'), ('1', '8:15 - 8:30'), ('2', '8:30 - 8:45'), ('3', '8:45 - 9:00'), ('4', '9:00 - 9:15'), ('5', '9:15 - 9:30'), ('6', '9:30 - 9:45'), ('7', '9:45 - 10:00'), ('8', '10:00 - 10:15'), ('9', '10:15 - 10:30'), ('10', '10:30 - 10:45'), ('11', '10:45 - 11:00'), ('12', '11:00 - 11:15'), ('13', '11:15 - 11:30'), ('14', '11:30 - 11:45'), ('15', '11:45 - 12:00'), ('16', '12:00 - 12:15'), ('17', '12:15 - 12:30'), ('18', '12:30 - 12:45'), ('19', '12:45 - 13:00'), ('20', '13:00 - 13:15'), ('21', '13:15 - 13:30'), ('22', '13:30 - 13:45'), ('23', '13:45 - 14:00'), ('24', '14:00 - 14:15'), ('25', '14:15 - 14:30'), ('26', '14:30 - 14:45'), ('27', '14:45 - 15:00'), ('28', '15:00 - 15:15'), ('29', '15:15 - 15:30'), ('30', '15:30 - 15:45'), ('31', '15:45 - 16:00'), ('32', '16:00 - 16:15'), ('33', '16:15 - 16:30'), ('34', '16:30 - 16:45'), ('35', '16:45 - 17:00'), ('36', '17:00 - 17:15'), ('37', '17:15 - 17:30'), ('38', '17:30 - 17:45'), ('39', '17:45 - 18:00'), ('40', '18:00 - 18:15'), ('41', '18:15 - 18:30'), ('42', '18:30 - 18:45'), ('43', '18:45 - 19:00')], default='0', max_length=2, verbose_name='Horario del turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Médico asignado'),
        ),
    ]
