# Generated by Django 5.0.3 on 2024-06-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0007_turno_delete_test'),
        ('turno', '0011_turno_area'),
    ]

    operations = [
    ]
