# Generated by Django 5.0.3 on 2024-07-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0012_alter_turno_options_turno_estado_alter_turno_horario_and_more'),
        ('turno', '0013_alter_turno_options_turno_area_turno_estado_and_more'),
    ]

    operations = [
    ]
