"""
Django settings for medicalsystem project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from unipath import Path
BASE_DIR = Path(__file__).ancestor(3)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-377=xvwje#p-!9a2*7^j9-+aw-2yb2gb59^96r9(pk!_vrv=@u'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tinymce',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.home',
    'apps.base',
    'apps.turno',
    'apps.socio',
    'apps.historialesclinicos',
    'ckeditor',
    'import_export',
]

LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'

TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'plugins': '''
        textcolor save link image media preview codesample contextmenu
        table code lists fullscreen  insertdatetime nonbreaking
        contextmenu directionality searchreplace wordcount visualblocks
        visualchars code fullscreen autolink lists  charmap print  hr
        anchor pagebreak
        ''',
    'toolbar': '''
        fullscreen preview bold italic underline | alignleft aligncenter
        alignright alignjustify | bullist numlist outdent indent | link
        image media | codesample |
        ''',
    'menubar': True,
    'statusbar': True,
    'importcss_append': True,
    'file_picker_types': 'image',
    'image_advtab': True,
}


JAZZMIN_SETTINGS = {
    "theme": "flatly",  # Tema predeterminado
    "dark_mode_theme": "darkly",  # Tema oscuro
    "topmenu_links": [
        # external url that opens in a new window (Permissions can be added)
        {"name": "Página de inicio", "url": "/", "new_window": False},
        {"name": "Administración de turnos", "url": "/turno/lista-turnos/", "new_window": True},
    ],
    "site_title": "MedicalSys",
    "site_header": "Library",
    "site_brand": "MedicalSys",
    "site_logo": "/img/base/Icono.png",
    "site_icon": "/img/base/Icono.png",
    "site_logo_classes": "img",
    "welcome_sign": "Ingresar las credenciales de administrador",
    "changeform_format": "carousel",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "socio.paciente": "fas fa-users",
        "socio.domicilio": "fas fa-home",
        "socio.parroquia": "fas fa-church",
        "socio.referente": "fas fa-cross",
        "socio.telefono": "fas fa-phone",
        "socio.certificado": "fas fa-print",
        "socio.tipocertificado": "fas fa-stamp",
    },
    }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medicalsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medicalsystem.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "es"


CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'height': 'auto', # Ajusta automáticamente la altura según el contenido
        'width': '100%', # Utiliza el 100% del ancho disponible
        'toolbar': [],  # Elimina todas las opciones de la barra de herramientas
        'removePlugins': 'elementspath', # Elimina la ruta del elemento
        'uiColor': '#FFFFFF',# Color de fondo de la interfaz
        'resize_enabled': True, # Habilita la capacidad de cambiar el tamaño del editor
    },
}





TIME_ZONE = 'America/Argentina/Buenos_Aires' 
USE_I18N = True
USE_L10N = True
USE_TZ = True

DATE_FORMAT = "%d/%m/%Y"

DEFAULT_CHARSET = 'utf-8'
